# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/swapi/planets
Content-Type: application/json

{
  "name": "Terra",
  "climate": "poor",
  "terrain": "bad"
}

###

GET http://localhost:8080/swapi/planets/search?name=Kamino
Accept: application/json

###

GET http://localhost:8080/swapi/planets/0c146a57-929b-4d45-bf79-e29235b8134e
Accept: application/json

###

GET http://localhost:8080/swapi/planets/
Accept: application/json

###

DELETE http://localhost:8080/swapi/planets/0c146a57-929b-4d45-bf79-e29235b8134e

###
