spring:
  application:
    name: StarWars REST API
  data:
    mongodb:
      uri: mongodb+srv://starwars:Do36dittJbfjTPcm@cluster0-avlwm.mongodb.net/starwarsapi?retryWrites=true
  output:
    ansi:
      enabled: detect

server:
  port: 8080
  servlet:
    context-path: /swapi
  http2:
    enabled: true
  compression:
    enabled: true
    mime-types: application/json

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
    file: "%d %-5level [%thread] %logger : %msg%n"
  level:
    root: info
    org.springframework.web: debug
    org.mongodb.driver: info
  file: starwarsapi.log

integrations:
  swapi:
    baseurl: "https://swapi.co/api/planets/"
